apiVersion: apps/v1
kind: Deployment
metadata:
  name: primerjalnik-izdelkov-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primerjalnik-izdelkov
  template:
    metadata:
      labels:
        app: primerjalnik-izdelkov
    spec:
      containers:
        - image: rsoskupina50/primerjavaizdelkov:2022-12-26-21-48-59
          name: primerjalnik-izdelkov
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/zzgixwih
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: zzgixwih
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: XwMg-3JIpwLWNylgwAP0bcQk3_dZmVFa
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /health/ready
                port: server
              initialDelaySeconds: 20
              periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: primerjalnik-izdelkov
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: primerjalnik-izdelkov
